config/routes.rb
Rails.application.routes.draw do
  resources :labels
  get 'sessions/new'
  resources :tasks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "tasks#index"
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]

  namespace :admin do
    resources :users
  end

end

app/models/task.rb
class Task < ApplicationRecord
        validates :title, presence: true
        validates :content, presence: true
        enum status: {未着手:0, 着手中:1, 完了:2}
        enum priority: {高:0, 中:1, 低:2}
        scope :search_title, -> (params_title) { where('title LIKE ?', "%#{params_title}%")}
        scope :search_status, -> (params_status) { where(status: params_status)}
        scope :search_label, -> (params_label) {
                task_ids = Labelling.where(label_id: params_label).pluck(:task_id)
                where(id: task_ids)
        }
        belongs_to :user 
        has_many :labellings, dependent: :destroy
        has_many :labels, through: :labellings
        # @tasks = @tasks.where(status: params[:status]) if params[:status] && params[:status] != ""

        # abcを定義した。引数はparams.
        # (params)仮引数は定義するものが仮に用意しておくもの。
        # 実引数はそのメソッドが使う側が使う引数のこと。
        # abcメソッドが使うのがコントローラー側。
        

        # scope :status_search, ->(params) { where(status: params) }
end
# やること
# ・scopeメソッドでステータス検索ができる
# ・scopeメソッドでタイトルとステータスの両方が検索できる
# わかったこと。
# ・paramsを受け取る
# ・
# わからないところ。
# ・

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  before_action :set_task, only: %i[ show edit update destroy ]

  
  # わかったこと
  # ・scopeとは、クラスメソッドを使う際、可読性を保つためにあるもの
  # ・書き方(Qiita見ながら)
  # ・viewから値を取ってくる　→ コントローラに渡す → コントローラ側で、scopeで使える形に変換→scopeに渡す
  # わからないところ。
  # ・viewから値をとってくる。とQiitaに記載されていたが、どうやって！どのようにして！
  # ・モデルを使うイメージがあったが。。。
  def index
    @tasks = current_user.tasks.order(created_at: :desc)
    @tasks = @tasks.reorder(expired_at: :desc) if params[:sort_expired]
    # @tasks = @tasks.search_title(params[:title]).search_status(params[:status]) if params[:title].present? && params[:status].present?
    @tasks = @tasks.search_title(params[:title]) if params[:title].present?
    @tasks = @tasks.search_status(params[:status]) if params[:status].present?
    @tasks = @tasks.reorder(priority: :asc) if params[:sort_priority]
    @tasks = @tasks.search_label(params[:label_id]) if params[:label_id].present?
    # @tasks = @tasks.joins(:labels).where(labels: { id: params[:label_id] }) if params[:label_id].present?
    @tasks = @tasks.page(params[:page]).per(6)
  end

  def show
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def create
    @task = current_user.tasks.build(task_params) #current_user.blogs.build は「ログイン中のユーザの、blogをbuild(new)する」という意味です。
    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_task
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:title, :content, :expired_at, :status, :task, :priority, { label_ids: [] })
      # □なぜタスクを追加したんだろう？
    end
  end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

    <div class="field">
    <%= form.label :expired_at %>
    <%= form.date_select :expired_at %>
  </div>
  
  <div class = "status-field">
    <%= form.label :ステータス %>
    <%= form.select :status, Task.statuses.keys, include_blank: true %>
  </div>

  <div class = "priority-field">
    <%= form.label :優先度 %>
    <%= form.select :priority, Task.priorities.keys, include_blank: true %>
  </div>

  <div class="field">
  <%= form.label :ラベル %>
    <%= form.collection_check_boxes(:label_ids, Label.all, :id, :name) %>
  </div>
  

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>


<h1>タスク一覧画面</h1>
  <%= form_with( url: tasks_path, method: :get, local: true) do |form| %>
  <%= form.label :タスク名 %>
  <%= form.text_field :title %>
  <%= form.label :ステータス %>
  <%# プルダウンで選択できるようにしている%>
  <%= form.select :status, Task.statuses.keys, include_blank: true %>
  <%# 上記一行はメソッドエラーが出た。Tasks#indexでこれらを受け取る設定をしてあげなければいけない。 %>
  <%# 9行目が当たっている確信がcontrollerでただしく受け取らない限りわからない。 %>
  <%= form.label :優先度 %>
  <%= form.select :priority, Task.priorities.keys, include_blank: true %>
  <%= form.submit '検索' %>
<% end %>

<%= form_with url: tasks_path, method: :get, local: true do |form| %>
  <%= form.select("label_id", Label.pluck(:name, :id), { include_blank: true }) %>
  <%= form.submit 'Search', name: nil %>
<% end %>

<table>
  <thead>
    <tr>
      <th>投稿者</th>
      <th>タスク</th>
      <th>内容</th>
      <th>終了期限</th>
      <th>ステータス</th>
      <th>優先度</th>
      <th>ラベル</th>
      <th colspan="4"></th>
      <%# コールスパンて何だよ！ %>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr class= "task_row">
        <td><%= task.user.name %></td>
        <td><%= task.title %></td>
        <td><%= task.content %></td>
        <td class = "task_expired_at"><%= task.expired_at %></td>
        <td><%= task.status %></td>
        <td><%= task.priority %></td>
        <td><%= link_to '詳細', task %></td>
        <td><%= link_to '編集', edit_task_path(task) %></td>
        <td><%= link_to '削除', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td>
      <% task.labels.each do |label| %>
        <%= label.name %>
      <% end %>
    </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate(@tasks) %>
<%# 上記はkaminariのview側に表示するための処理である。 %>

<br>

<%= link_to '新規タスク登録', new_task_path %>
<%= link_to "終了期限でソートする", tasks_path(sort_expired: "true") %>
<%= link_to "優先度をソートする", tasks_path(sort_priority: "true") %>
<%= link_to "管理者画面へ移動する",admin_users_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @task.content %>
</p>

<p>
  <strong>Expired_at:</strong>
  <%= @task.expired_at %>
</p>

<p>
  <strong>ステータス:</strong>
  <%= @task.status %>
</p>

<p>
  <strong>優先度:</strong>
  <%= @task.priority %>
</p>

<p>
  <strong>ラベル:</strong>
  <% @task.labels.each do |label| %>
    <%= label.name %>
  <% end %>
</p>


<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>