config/routes.rb
Rails.application.routes.draw do
  resources :labels
  get 'sessions/new'
  resources :tasks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "tasks#index"
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]

  namespace :admin do
    resources :users
  end

end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  # before_destroy :final_admin_destroy
  # before_destroy :final_admin_update
  after_destroy :admin_necessary
  after_update :admin_necessary
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :tasks
  
#   def final_admin_destroy
#     if User.where(admin: 'true').count <= 1 && self.admin == true
#       throw :abort
#     end
#   end

#   def final_admin_update
#     if User.where(admin: 'true').count == 1 && self.admin == false
#       throw :abort
#   end
# end

def admin_necessary
  if User.where(admin: 'true').count == 0
    raise ActiveRecord::Rollback
  end
end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  before_action :admin_user
  # skip_before_action :admin_user
  # 上記ArgumentErrorが発生した。
  # login?required が定義されていないとケラー分が出ている。
  # 仮説：login_requiredが存在しているかを確認すべきである。
  # そもそも skip_before_actionの定義をちゃんと理解すべきである。
  # また記載する場所の確認も必要だ。
    def index
      @users = User.all.page(params[:page]).per(6)
    end

    def new
      @user = User.new
    end
  
    def create
      @user = User.new(user_params)
      if @user.save
        redirect_to admin_users_path
        # _pathっているっけ？ 後で確認しなくきゃ
      else
        render :new
      end
    end
  
    def show
      @user = User.find(params[:id])
    end

    def edit
      @user = User.find(params[:id])
      # NoMethodError in Admin::Users#edit
      # editの内容を削除すると、上記のエラーが生じてしまうのでだめだ。でもtaskはなんでeditの中身がないのに編集できるんだ？
    end

    def update
      # そもそもなんでbinding.pryで止まらないんだ。
      # 処理が来てない？ いやでも、
      @user = User.find(params[:id])
      if @user.update(user_params)
        redirect_to admin_users_path
      else
        render :edit
    end
  end

  # def final_admin_destroy
  #   @user = User.find(params[:id])
  #   if @user.destroy
  #   redirect_to admin_users_path, notice:"ブログを削除しました！"
  #   else 
  #     redirect_to admin_users_path, notice:"きえて"
  #   end
  # end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
    redirect_to admin_users_path, notice:"ブログを削除しました！"
    else 
      redirect_to admin_users_path, notice:"なぜか消せませんでした。"
    end
  end

  private
  def admin_user
    unless current_user.admin?
      redirect_to tasks_path
      flash[:notice] = '管理者以外はアクセスできない'
    end
  end

  
      def user_params
        params.require(:user).permit(:name, :email, :password,
          :password_confirmation, :admin)
        end
  end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  before_action :signup_not, only: [:new, :create]
  # 上記ArgumentErrorが発生した。
  # login?required が定義されていないとケラー分が出ている。
  # 仮説：login_requiredが存在しているかを確認すべきである。
  # そもそも skip_before_actionの定義をちゃんと理解すべきである。
  # また記載する場所の確認も必要だ。
  def new
    @user = User.new

  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
      # _pathっているっけ？ 後で確認しなくきゃ
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @tasks = @user.tasks
  end
      private
    def user_params
      params.require(:user).permit(:name, :email, :password,
        :password_confirmation, :admin)
      end
 
      def signup_not
        redirect_to tasks_path if current_user
      end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<h1>管理者用ユーザー編集画面</h1>

<%= form_with(model: @user, url: admin_user_path(@user.id),  local: true) do |form| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
            
            <ul>
            <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
            </ul>
            </div>
            <% end %>
            <div class="field">
            <%= form.label :name, '名前' %>
            <%= form.text_field :name %>
            </div>
            <div class="field">
            <%= form.label :email, 'メールアドレス' %>
            <%= form.text_field :email %>
            </div>
            <div class="field">
            <%= form.label :password, 'パスワード' %>
            <%= form.password_field :password %>
            </div>
            
            <div class = "field">
            <%= form.label :password_confirmation, 'パスワード確認' %>
            <%= form.password_field :password_confirmation %>
            
            </div>

             <div class = "field">
        <%= form.label :管理者権限 %>
  <%= form.select :admin, [["管理者","true"],["一般","false"]] %>
            
            </div>
            
            <div class="actions">
            <%= form.submit %>
            
            </div>
            
            <% end %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', admin_users_path %>

app/views/admin/users/index.html.erb
<p id="notice"><%= notice %></p>


<h1>管理者画面</h1>
    <%= form_with( url: tasks_path, method: :get, local: true) do |form| %>
    <%= form.label :タスク名 %>
    <%= form.text_field :title %>
    <%= form.label :ステータス %>
    <%# プルダウンで選択できるようにしている%>
    <%= form.select :status, Task.statuses.keys, include_blank: true %>
    <%# 上記一行はメソッドエラーが出た。Tasks#indexでこれらを受け取る設定をしてあげなければいけない。 %>
    <%# 9行目が当たっている確信がcontrollerでただしく受け取らない限りわからない。 %>
    <%= form.label :優先度 %>
    <%= form.select :priority, Task.priorities.keys, include_blank: true %>
    <%= form.submit '検索' %>
<% end %>

<table>
    <thead>
    <tr>
        <th>投稿者</th>
        <th>タスク</th>
        <th>内容</th>
        <th>終了期限</th>
        <th>ステータス</th>
        <th>優先度</th>
        <th colspan="4"></th>
        <%# コールスパンて何だよ！ %>
    </tr>
    </thead>

    <tbody>
    <% @users.each do |user| %>
        <tr class= "task_row">
            <td><%= user.name %></td>
            <td><%= user.email %></td>
            <td><%= link_to '詳細', user %></td>
            <td><%= link_to '編集', edit_admin_user_path(user) %></td>
            <td><%= link_to '削除', admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
    </tbody>
</table>
<%= paginate(@users) %>
<br>

<%= link_to '管理者ユーザー新規登録へ', new_admin_user_path %>

app/views/admin/users/new.html.erb
<h1>管理者新規ユーザー登録</h1>

<%= form_with(model: @user, url: admin_users_path,  local: true) do |form| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, '名前' %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email, 'メールアドレス' %>
    <%= form.text_field :email %>
  </div>

    <div class="field">
    <%= form.label :password, 'パスワード' %>
    <%= form.password_field :password %>
  </div>
  
  <div class = "field">
    <%= form.label :password_confirmation, 'パスワード確認' %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', admin_users_path %>

app/views/admin/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @task.content %>
</p>

<p>
  <strong>Expired_at:</strong>
  <%= @task.expired_at %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>